name: Deploy Frontend on PR Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy frontend
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            if [ ! -d ~/qs-frontend ]; then
              git clone git@github.com:marcomartinscastanho/quiz-stats-frontend.git ~/qs-frontend
            fi
            cd ~/qs-frontend
            git pull origin main
            docker compose -f docker-compose.prod.yml up --build -d
          EOF
